linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0.8

linters:
  enable:
    - govet
    - gocyclo
    - errcheck
    - unused
    - ineffassign
    - typecheck
    - gosimple
    - stylecheck

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should have comment or be unexported"
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"

run:
  deadline: 5m