name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-formatting:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5


  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Run golangci-lint
        run: |
          golangci-lint run --config .golangci.yml

  code-coverage:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: [code-formatting, lint]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}