name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-formatting:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5


  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.55.2
          args: --config .golangci.yml

  code-coverage:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: [code-formatting, lint]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}